server:
  port: 8081

#nacos:
#  config:
#    # 指定命名空间
#    namespace: 30e4480b-f903-4d26-8084-cedff611a340
#    #配置服务地址
#    server-addr: localhost:8848
#    username: nacos
#    password: nacos
#    #data-ids 为新增加的data-id
#    data-id: dubbo3-consumer
#    #配置类型
#    type: yaml
#    #是否启动刷新配置，开启之后可适应
#    autoRefresh: true
#    #运行时启用
#    bootstrap:
#      enable: true

dubbo:
  application:
    name: dubbo-consumer
    version: 1.0.0
    qos-enable: false
  registry:
      address: nacos://localhost:8848?namespace=30e4480b-f903-4d26-8084-cedff611a340&username=nacos&password=nacos
  protocol:
    name: dubbo
#    port: 20880